export interface DietTip {
    emoji: string;
    text: string;
}

export const DIET_TIPS: DietTip[] = [
    // --- GYM BRO LOGIC (Funny but True) ---
    { emoji: '🏋️', text: 'If you can\'t lift it, stare at it until it gets lighter. (Just kidding, lower the weight).' },
    { emoji: '💔', text: 'Heartbreak is the best pre-workout. Use the pain.' },
    { emoji: '🦵', text: 'Skipping leg day is a sin punishable by chicken legs.' },
    { emoji: '💪', text: 'Curls in the squat rack? Straight to jail.' },
    { emoji: '🤝', text: 'A gym bro is for life, not just for Christmas.' },
    { emoji: '👕', text: 'Wear a hoodie until you\'re big enough to fill a t-shirt.' },
    { emoji: '🚿', text: 'If you don\'t look like a wet rat after cardio, you didn\'t do cardio.' },
    { emoji: '🦄', text: 'Supplements won\'t fix your trash diet. Sorry.' },
    { emoji: '🚑', text: 'If you die, you die. But don\'t drop the weights.' },
    { emoji: '🧪', text: 'Creatine isn\'t steroids. Your mom is just dramatic.' },
    { emoji: '🍑', text: 'Glutes are for everyone. Yes, you too, bro.' },
    { emoji: '🤳', text: 'If you didn\'t take a mirror selfie, did you even go to the gym?' },
    { emoji: '👚', text: 'Re-racking weights is the ultimate sign of an alpha.' },
    { emoji: '🛑', text: 'Ego lifting builds injuries, not muscles.' },
    { emoji: '🎧', text: 'Forgot headphones? Might as well go home.' },
    { emoji: '🏗️', text: 'Building muscle is like watching paint dry. But the paint is heavy.' },
    { emoji: '🥜', text: 'A peanut is not a nut. It\'s a legume. And it\'s making you fat.' },
    { emoji: '🥛', text: 'GOMAD (Gallon Of Milk A Day)? RIP your toilet.' },
    { emoji: '🧘', text: 'Stretching is boring. Being stiff like a board is worse.' },
    { emoji: '🦖', text: 'T-Rex mode activated: Big legs, tiny arms. Don\'t be that guy.' },
    { emoji: '🦍', text: 'Return to monke. Lift heavy stone.' },
    { emoji: '🍗', text: 'Chicken breast again? Yes. Cry about it while you eat.' },
    { emoji: '🛌', text: 'Rest days are for growing. Gym days are for breaking.' },
    { emoji: '🤸', text: 'Calisthenics guys are just gymnasts who can\'t afford a gym membership. (Jk, much respect).' },
    { emoji: '🧼', text: 'Wash your gym clothes. We can smell you from the parking lot.' },

    // --- DIET HACKS (Useful) ---
    { emoji: '💧', text: 'Drink a glass of water before every meal. Instant portion control.' },
    { emoji: '🍽️', text: 'Use a smaller plate. It tricks your brain into thinking you ate more.' },
    { emoji: '🍫', text: 'Craving chocolate? Eat a square of 80% dark. You won\'t want a second one.' },
    { emoji: '🥗', text: 'Eat your veggies first. Fills you up before the fun stuff.' },
    { emoji: '🧂', text: 'Spices add flavor, not calories. Go crazy with cumin and chilli.' },
    { emoji: '🍎', text: 'An apple is nature\'s caffeine. Wakes you up better than coffee.' },
    { emoji: '🥔', text: 'Boiled potatoes are the most satiating food on earth. Use them.' },
    { emoji: '🍳', text: 'Don\'t toss the yolks! That\'s where the vitamins live.' },
    { emoji: '🍌', text: 'Bananas are nature\'s energy bar. Comes with its own wrapper.' },
    { emoji: '☕', text: 'Black coffee blunts appetite. Use it for intermittent fasting.' },
    { emoji: '🥤', text: 'Don\'t drink your calories. Coke is liquid sugar. Drink water.' },
    { emoji: '🧊', text: 'Cold water burns 8 calories per glass. It ain\'t much, but it\'s honest work.' },
    { emoji: '🥑', text: 'Fat doesn\'t make you fat. Excess calories make you fat.' },
    { emoji: '🍚', text: 'Rice isn\'t the enemy. Eating a mountain of it is.' },
    { emoji: '🍦', text: 'Halo Top or Greek Yogurt > Ben & Jerry\'s.' },
    { emoji: '🥘', text: 'Cooking your own food is the #1 way to get ripped.' },
    { emoji: '🍬', text: 'Sugar crash is real. Avoid candy pre-workout.' },
    { emoji: '🧂', text: 'Sodium is necessary for pumps. Don\'t fear the salt shaker.' },
    { emoji: '🥜', text: 'Nuts are calorie bombs. Measure them, don\'t handful them.' },
    { emoji: '🥣', text: 'Oats are great, but instant oats are just sugar. Get rolled oats.' },
    { emoji: '🍯', text: 'Honey is sugar. It\'s natural, but it\'s still sugar.' },
    { emoji: '🥫', text: 'Read the label. If "Sugar" is in the top 3 ingredients, put it back.' },
    { emoji: '🍴', text: 'Chew slowly. Digestion starts in the mouth.' },
    { emoji: '🏃', text: 'Don\'t eat right before a run. You will regret it.' },
    { emoji: '🚽', text: 'Coffee + Pre-workout = dangerous game. Know your nearest toilet.' },

    // --- NEPALI CONTEXT (Cultural & Funny) ---
    { emoji: '🍛', text: 'Dal Bhat Power 24 Hour? Only if you don\'t sleep for 12 of them.' },
    { emoji: '🥟', text: 'Momo is an emotion, not a food group. Limit to once a week.' },
    { emoji: '🧱', text: 'Satu is the OG protein shake. Your grandpa was ripped for a reason.' },
    { emoji: '🥓', text: 'Sukuti is high protein but high sodium. Drink water!' },
    { emoji: '🧈', text: 'Ghee is good, but don\'t drown your rice in it.' },
    { emoji: '🥒', text: 'Gundruk is a gut health superfood. Smell is free.' },
    { emoji: '☕', text: 'Chiya biscuits? That\'s just sugar dipping in sugar. Stop it.' },
    { emoji: '🍜', text: 'Chowmein is just oil and flour. It\'s barely food.' },
    { emoji: '🥘', text: 'Khichdi > Pizza when you\'re sick. Trust the ancestors.' },
    { emoji: '🌶️', text: 'Akbare Khursani boosts metabolism. And pain.' },
    { emoji: '🦷', text: 'Churpi fits your macros and cleans your teeth. Win-win.' },
    { emoji: '🍚', text: 'Beat that Chiura bloat with water. It expands!' },
    { emoji: '🍗', text: 'Sekuwa > Fried Chicken. Less oil, more fire.' },
    { emoji: '🥣', text: 'Thukpa is healthy if you add eggs and meat. Otherwise it\'s just soup.' },
    { emoji: '🏚️', text: 'Don\'t trust "Diet" food in Kathmandu restaurants. It\'s a lie.' },
    { emoji: '🍺', text: 'Raksi kills gains. Sorry to break it to you.' },
    { emoji: '🥜', text: 'Badam Sadeko is a protein bomb. But also a fart bomb.' },
    { emoji: '🌽', text: 'Polleko Makai is the best street snack. Cheap and carb-loaded.' },
    { emoji: '🚴', text: 'Kathmandu dust is not a supplement. Wear a mask.' },
    { emoji: '🍽️', text: 'Eating with hands tastes better. Science can\'t explain it.' },
    { emoji: '🐕', text: 'Running from street dogs is excellent HIIT cardio.' },
    { emoji: '🌞', text: 'Determine workout time by pollution levels, not choices.' },
    { emoji: '🧘', text: 'Vipassana will clear your mind, but squats clear your stress.' },
    { emoji: '🍖', text: 'Whole goat curry? Eat the meat, skip the skin/fat.' },
    { emoji: '🥛', text: 'Dahi (Curd) gives you huge muscles. Look at the wrestlers.' },

    // --- HARD TRUTHS (Motivational) ---
    { emoji: '💀', text: 'No one cares about your excuses. Not even your mom.' },
    { emoji: '🤥', text: 'You\'re not hungry, you\'re bored. Go for a walk.' },
    { emoji: '📉', text: 'Consistency beats intensity. Stop going hard for 1 week and quitting.' },
    { emoji: '📱', text: 'Stop scrolling TikTok between sets. You\'re cooling down too much.' },
    { emoji: '🛌', text: 'You can\'t out-train 4 hours of sleep.' },
    { emoji: '🍕', text: 'One salad won\'t make you skinny. One pizza won\'t make you fat.' },
    { emoji: '🤔', text: 'Motivation is a feeling. Discipline is an action. Choose action.' },
    { emoji: '🕰️', text: 'You have exactly the same number of hours as Arnold. Use them.' },
    { emoji: '👎', text: 'Being "too busy" is a lie. You just didn\'t prioritize it.' },
    { emoji: '🔥', text: 'Soreness is weakness leaving the body. Or bad form. Check your form.' },
    { emoji: '🗣️', text: 'Your body hears everything your mind says. Be nice.' },
    { emoji: '🎯', text: 'If you aim at nothing, you will hit it every time.' },
    { emoji: '🥈', text: 'Second place is the first loser. Train to win.' },
    { emoji: '🤷', text: 'Genetics load the gun, lifestyle pulls the trigger.' },
    { emoji: '🧊', text: 'Discomfort is the price of admission to a better life.' },
    { emoji: '🚪', text: 'Leave your ego at the door. Lift properly.' },
    { emoji: '🪞', text: 'The mirror doesn\'t lie. The scale might, but the mirror doesn\'t.' },
    { emoji: '🧠', text: 'Your mind gives up 10 reps before your body does.' },
    { emoji: '⏳', text: 'A one hour workout is 4% of your day. No excuses.' },
    { emoji: '🚶', text: 'Walking is the most underrated fat loss tool. Just walk.' },
    { emoji: '🚮', text: 'Treat your body like a temple, not a trash can.' },
    { emoji: '🌧️', text: 'Rain is just free cooling. Go run.' },
    { emoji: '🦁', text: 'Sheep follow the herd. Lions hunt alone. Or with a spotter.' },
    { emoji: '🚫', text: 'Quitting now puts you back to where you started. And you hated it there.' },
    { emoji: '🏆', text: 'Champions are made when no one is watching.' },

    // --- SCIENCE & HEALTH (Facts) ---
    { emoji: '😴', text: 'Sleep is the best steroid. 8 hours minimum for growth.' },
    { emoji: '🧪', text: 'Protein has a high TEF (Thermic Effect). You burn calories digestion it.' },
    { emoji: '☀️', text: 'Morning sunlight sets your circadian rhythm. Improved sleep tonight.' },
    { emoji: '🥶', text: 'Cold exposure increases dopamine by 250%.' },
    { emoji: '🧴', text: 'Magnesium helps you relax. Most people are deficient.' },
    { emoji: '🦴', text: 'Lifting weights increases bone density. Don\'t break a hip at 60.' },
    { emoji: '🫀', text: 'Cardio improves heart health. A strong heart pumps better pumps.' },
    { emoji: '🧠', text: 'Exercise promotes neuroplasticity. Use your brain or lose it.' },
    { emoji: '🧘', text: 'Cortisol (stress) eats muscle. Relax to grow.' },
    { emoji: '🩸', text: 'High insulin blocks fat burning. Fasting lowers insulin.' },
    { emoji: '💊', text: 'Vitamin D is a hormone, not a vitamin. Get tested.' },
    { emoji: '🐟', text: 'Omega-3s reduce inflammation. Less pain, more gain.' },
    { emoji: '🦠', text: 'Gut health controls your mood (serotonin). Eat fiber.' },
    { emoji: '👅', text: 'Sugar is 8x more addictive than cocaine in rats. Break the habit.' },
    { emoji: '🚽', text: 'Hydration status: If it\'s yellow, you\'re mellow. If it\'s brown, you\'re down.' },
    { emoji: '🔄', text: 'Muscle memory is real. Rebuilding is faster than building.' },
    { emoji: '🦵', text: 'Squats release testosterone and HGH naturally.' },
    { emoji: '👁️', text: '20-20-20 rule: Screen time strains eyes. Look 20ft away every 20 mins.' },
    { emoji: '🦷', text: 'Oral health is linked to heart health. Floss.' },
    { emoji: '🧍', text: 'Sitting is the new smoking. Stand up every hour.' },
    { emoji: '🚶', text: '10,000 steps burns ~400 cals. That\'s a whole meal.' },
    { emoji: '💧', text: 'Thirst is often confused with hunger. Drink first.' },
    { emoji: '🤕', text: 'Active recovery (walking/swimming) heals faster than rotting in bed.' },
    { emoji: '🌡️', text: 'Sauna use mimics moderate cardio. Good for the heart.' },
    { emoji: '👃', text: 'Nose breathing filters air and increases oxygen uptake.' },

    // --- LIFE HACKS (Practical) ---
    { emoji: '🛒', text: 'Never shop hungry. You will buy junk.' },
    { emoji: '🥡', text: 'Meal prep prevents bad decisions.' },
    { emoji: '📝', text: 'Track it. If you don\'t measure it, you can\'t manage it.' },
    { emoji: '🎧', text: 'Audiobooks turning commute time into learning time.' },
    { emoji: '🧹', text: 'Cleaning your room burns calories. Do it.' },
    { emoji: '🚿', text: 'Cold shower wakes you up faster than coffee.' },
    { emoji: '⏰', text: 'Put your alarm across the room. Force yourself to stand up.' },
    { emoji: '👖', text: 'Wear gym clothes to bed? One less step in the morning.' },
    { emoji: '📵', text: 'No phone in the bedroom. Sleep hygiene 101.' },
    { emoji: '📅', text: 'Schedule your workouts like meetings. Non-negotiable.' },
    { emoji: '🤝', text: 'Accountability partner increases success rate by 95%.' },
    { emoji: '📷', text: 'Take progress pics. The scale is a liar.' },
    { emoji: '👟', text: 'Buy good shoes. Your knees will thank you.' },
    { emoji: '🎒', text: 'Pack your gym bag the night before.' },
    { emoji: '🚲', text: 'Commute by bike. Save money, burn fat.' },
    { emoji: '📺', text: 'Do planks during TV commercials.' },
    { emoji: ' лест', text: 'Take the stairs. Every time.' },
    { emoji: '🦷', text: 'Brush teeth after dinner to signal "kitchen closed".' },
    { emoji: '🥶', text: 'Turn down the heat. Body burns cals keeping warm.' },
    { emoji: '🍵', text: 'Green tea boosts metabolism slightly.' },
    { emoji: '🍽️', text: 'Put your fork down between bites. Slow down.' },
    { emoji: '🧂', text: 'Pink salt has... trace minerals? Just tastes good.' },
    { emoji: '🧼', text: 'Wash your hands. Don\'t get sick and lose a week of training.' },
    { emoji: '🛌', text: 'Invest in a good mattress. You spend 1/3 of life there.' },
    { emoji: '🧠', text: 'Visualization works. Imagine the lift before you do it.' }
];
